
[[constraint]]
  name = "github.com/heroku/docker-registry-client"
  source = "github.com/weaveworks/docker-registry-client"
  branch = "master"

[[override]]
  name = "github.com/ugorji/go"
  revision = "8c0409fcbb70099c748d71f714529204975f6c3f"
